# Generated by Django 4.2.2 on 2023-06-06 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelapi', '0004_alter_trip_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_locations', to='travelapi.location')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_locations', to='travelapi.trip')),
            ],
        ),
        migrations.AddField(
            model_name='trip',
            name='locations',
            field=models.ManyToManyField(related_name='trip_places', to='travelapi.triplocation'),
        ),
    ]
