# Generated by Django 4.2.2 on 2023-06-07 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelapi', '0005_triplocation_trip_locations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityitinerary',
            name='day',
        ),
        migrations.RemoveField(
            model_name='activityitinerary',
            name='itinerary',
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='details',
        ),
        migrations.AddField(
            model_name='activity',
            name='booking_link',
            field=models.CharField(default='a link', max_length=500),
        ),
        migrations.AddField(
            model_name='activity',
            name='description',
            field=models.CharField(default='An activity', max_length=500),
        ),
        migrations.AddField(
            model_name='activity',
            name='minimum_duration',
            field=models.CharField(default='1hr', max_length=50),
        ),
        migrations.AddField(
            model_name='activity',
            name='picture',
            field=models.CharField(default='image link', max_length=500),
        ),
        migrations.AddField(
            model_name='activityitinerary',
            name='trip',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='activity_itinerary', to='travelapi.trip'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='details',
            field=models.ManyToManyField(related_name='itinerary_details', to='travelapi.activityitinerary'),
        ),
    ]
