# Generated by Django 4.2.2 on 2023-06-08 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapi', '0006_remove_activityitinerary_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
