# Generated by Django 4.2.2 on 2023-06-08 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapi', '0007_alter_activity_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='booking_link',
            new_name='website',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='minimum_duration',
        ),
        migrations.AddField(
            model_name='activity',
            name='rating',
            field=models.CharField(default='4', max_length=10),
        ),
    ]
