# Generated by Django 4.2.2 on 2023-06-09 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapi', '0010_activity_lat_activity_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='lat',
            field=models.FloatField(default=40.7128, max_length=30),
        ),
        migrations.AlterField(
            model_name='activity',
            name='lng',
            field=models.FloatField(default=74.006, max_length=30),
        ),
    ]
