# Generated by Django 4.2.2 on 2023-06-12 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelapi', '0012_packing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('place_id', models.CharField(default='link', max_length=100)),
                ('rating', models.CharField(default='4', max_length=10)),
                ('vicinity', models.CharField(default='somewhere', max_length=50)),
                ('lat', models.FloatField(default=40.7128, max_length=30)),
                ('lng', models.FloatField(default=74.006, max_length=30)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelapi.location')),
            ],
        ),
    ]
