# Generated by Django 4.2.2 on 2023-06-13 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelapi', '0013_hotel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_date', models.CharField(max_length=20)),
                ('transport_type', models.CharField(max_length=20)),
                ('dep_time', models.CharField(max_length=20)),
                ('arr_time', models.CharField(max_length=20)),
                ('arr_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='travelapi.location')),
                ('dep_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='travelapi.location')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelapi.trip')),
            ],
        ),
    ]
