# Generated by Django 4.2.2 on 2023-06-13 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapi', '0014_travel'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='image',
            field=models.CharField(default='https://mail.google.com/mail/u/0?ui=2&ik=d893f429cf&attid=0.1.1&permmsgid=msg-f:1767541423958244148&th=1887918f6cd1bb34&view=fimg&fur=ip&sz=s0-l75-ft&attbid=ANGjdJ95c40vVKXqgO0e9LrAiKHqbAXDkCDO8-RdHTQ6fN-hUMhuBFv1aHRqSP4BmfGrN66PZx5jsJBtXR_yOmRKY9qiCLUKqJhZZNUFU0_Yd-oLu6BxxS3iy4sGWis&disp=emb', max_length=300),
        ),
    ]
