# Generated by Django 4.2.2 on 2023-06-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapi', '0015_trip_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='vicinity',
            field=models.CharField(default='somewhere', max_length=100),
        ),
    ]
