# Generated by Django 4.2.2 on 2023-06-16 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelapi', '0016_alter_activity_vicinity'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='trip',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='travelapi.trip'),
            preserve_default=False,
        ),
    ]
