# Generated by Django 4.2.2 on 2023-06-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapi', '0019_tripexpenses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='expenses',
            field=models.ManyToManyField(related_name='budgetSpending', to='travelapi.tripexpenses'),
        ),
    ]
